// SYSTEM_INFORMATION
export const GET_SYSTEM_INFORMATION_PENDING = 'GET_SYSTEM_INFORMATION_PENDING';
export const GET_SYSTEM_INFORMATION_SUCCESS = 'GET_SYSTEM_INFORMATION_SUCCESS';
export const GET_SYSTEM_INFORMATION_FAILURE = 'GET_SYSTEM_INFORMATION_FAILURE';

// PAGE MANAGEMENT
export const CREATE_PAGE_PENDING = 'CREATE_PAGE_PENDING';
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS';
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE';

export const FETCH_PAGES_PENDING = 'FETCH_PAGES_PENDING';
export const FETCH_PAGES_SUCCESS = 'FETCH_PAGES_SUCCESS';
export const FETCH_PAGES_FAILURE = 'FETCH_PAGES_FAILURE';

export const FETCH_PAGE_PENDING = 'FETCH_PAGE_PENDING';
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS';
export const FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE';

export const UPDATE_PAGE_PENDING = 'UPDATE_PAGE_PENDING';
export const UPDATE_PAGE_SUCCESS = 'UPDATE_PAGE_SUCCESS';
export const UPDATE_PAGE_FAILURE = 'UPDATE_PAGE_FAILURE';

export const DELETE_PAGE_PENDING = 'DELETE_PAGE_PENDING';
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS';
export const DELETE_PAGE_FAILURE = 'DELETE_PAGE_FAILURE';

export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_BY_ID_PENDING = 'FETCH_PRODUCT_BY_ID_PENDING';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';

export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

export const CREATE_PRODUCT_SIZE_PENDING = 'CREATE_PRODUCT_SIZE_PENDING';
export const CREATE_PRODUCT_SIZE_SUCCESS = 'CREATE_PRODUCT_SIZE_SUCCESS';
export const CREATE_PRODUCT_SIZE_FAILURE = 'CREATE_PRODUCT_SIZE_FAILURE';

export const UPDATE_PRODUCT_SIZE_PENDING = 'UPDATE_PRODUCT_SIZE_PENDING';
export const UPDATE_PRODUCT_SIZE_SUCCESS = 'UPDATE_PRODUCT_SIZE_SUCCESS';
export const UPDATE_PRODUCT_SIZE_FAILURE = 'UPDATE_PRODUCT_SIZE_FAILURE';

export const DELETE_PRODUCT_SIZE_PENDING = 'DELETE_PRODUCT_SIZE_PENDING';
export const DELETE_PRODUCT_SIZE_SUCCESS = 'DELETE_PRODUCT_SIZE_SUCCESS';
export const DELETE_PRODUCT_SIZE_FAILURE = 'DELETE_PRODUCT_SIZE_FAILURE';

export const CREATE_PRODUCT_QUANTITY_PENDING =
  'CREATE_PRODUCT_QUANTITY_PENDING';
export const CREATE_PRODUCT_QUANTITY_SUCCESS =
  'CREATE_PRODUCT_QUANTITY_SUCCESS';
export const CREATE_PRODUCT_QUANTITY_FAILURE =
  'CREATE_PRODUCT_QUANTITY_FAILURE';

export const UPDATE_PRODUCT_QUANTITY_PENDING =
  'UPDATE_PRODUCT_QUANTITY_PENDING';
export const UPDATE_PRODUCT_QUANTITY_SUCCESS =
  'UPDATE_PRODUCT_QUANTITY_SUCCESS';
export const UPDATE_PRODUCT_QUANTITY_FAILURE =
  'UPDATE_PRODUCT_QUANTITY_FAILURE';

export const DELETE_PRODUCT_QUANTITY_PENDING =
  'DELETE_PRODUCT_QUANTITY_PENDING';
export const DELETE_PRODUCT_QUANTITY_SUCCESS =
  'DELETE_PRODUCT_QUANTITY_SUCCESS';
export const DELETE_PRODUCT_QUANTITY_FAILURE =
  'DELETE_PRODUCT_QUANTITY_FAILURE';

export const PRODUCT_IMAGE_UPLOAD_PENDING = 'PRODUCT_IMAGE_UPLOAD_PENDING';
export const PRODUCT_IMAGE_UPLOAD_SUCCESS = 'PRODUCT_IMAGE_UPLOAD_SUCCESS';
export const PRODUCT_IMAGE_UPLOAD_FAILURE = 'PRODUCT_IMAGE_UPLOAD_FAILURE';

export const GET_ATTRIBUTES_PENDING = 'GET_ATTRIBUTES_PENDING';
export const GET_ATTRIBUTES_SUCCESS = 'GET_ATTRIBUTES_SUCCESS';
export const GET_ATTRIBUTES_FAILURE = 'GET_ATTRIBUTES_FAILURE';

export const GET_ATTRIBUTES_BY_ID_PENDING = 'GET_ATTRIBUTES_BY_ID_PENDING';
export const GET_ATTRIBUTES_BY_ID_SUCCESS = 'GET_ATTRIBUTES_BY_ID_SUCCESS';
export const GET_ATTRIBUTES_BY_ID_FAILURE = 'GET_ATTRIBUTES_BY_ID_FAILURE';

export const UPDATE_ATTRIBUTES_PENDING = 'UPDATE_ATTRIBUTES_PENDING';
export const UPDATE_ATTRIBUTES_SUCCESS = 'UPDATE_ATTRIBUTES_SUCCESS';
export const UPDATE_ATTRIBUTES_FAILURE = 'UPDATE_ATTRIBUTES_FAILURE';

export const DELETE_ATTRIBUTES_PENDING = 'DELETE_ATTRIBUTES_PENDING';
export const DELETE_ATTRIBUTES_SUCCESS = 'DELETE_ATTRIBUTES_SUCCESS';
export const DELETE_ATTRIBUTES_FAILURE = 'DELETE_ATTRIBUTES_FAILURE';

export const GET_SYSTEM_SETTINGS_PENDING = 'GET_SYSTEM_SETTINGS_PENDING';
export const GET_SYSTEM_SETTINGS_SUCCESS = 'GET_SYSTEM_SETTINGS_SUCCESS';
export const GET_SYSTEM_SETTINGS_FAILURE = 'GET_SYSTEM_SETTINGS_FAILURE';

export const UPDATE_SYSTEM_SETTINGS_PENDING = 'UPDATE_SYSTEM_SETTINGS_PENDING';
export const UPDATE_SYSTEM_SETTINGS_SUCCESS = 'UPDATE_SYSTEM_SETTINGS_SUCCESS';
export const UPDATE_SYSTEM_SETTINGS_FAILURE = 'UPDATE_SYSTEM_SETTINGS_FAILURE';

export const FETCH_SUPPLIERS_PENDING = 'FETCH_SUPPLIERS_PENDING';
export const FETCH_SUPPLIERS_SUCCESS = 'FETCH_SUPPLIERS_SUCCESS';
export const FETCH_SUPPLIERS_FAILURE = 'FETCH_SUPPLIERS_FAILURE';

export const FETCH_SUPPLIER_PROFILE_PENDING = 'FETCH_SUPPLIER_PROFILE_PENDING';
export const FETCH_SUPPLIER_PROFILE_SUCCESS = 'FETCH_SUPPLIER_PROFILE_SUCCESS';
export const FETCH_SUPPLIER_PROFILE_FAILURE = 'FETCH_SUPPLIER_PROFILE_FAILURE';

export const UPDATE_SUPPLIER_PROFILE_PENDING =
  'UPDATE_SUPPLIER_PROFILE_PENDING';
export const UPDATE_SUPPLIER_PROFILE_SUCCESS =
  'UPDATE_SUPPLIER_PROFILE_SUCCESS';
export const UPDATE_SUPPLIER_PROFILE_FAILURE =
  'UPDATE_SUPPLIER_PROFILE_FAILURE';

export const FETCH_STAFF_PENDING = 'FETCH_STAFF_PENDING';
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS';
export const FETCH_STAFF_FAILURE = 'FETCH_STAFF_FAILURE';

export const FETCH_STAFF_PROFILE_PENDING = 'FETCH_STAFF_PROFILE_PENDING';
export const FETCH_STAFF_PROFILE_SUCCESS = 'FETCH_STAFF_PROFILE_SUCCESS';
export const FETCH_STAFF_PROFILE_FAILURE = 'FETCH_STAFF_PROFILE_FAILURE';

export const UPDATE_STAFF_PROFILE_PENDING = 'UPDATE_STAFF_PROFILE_PENDING';
export const UPDATE_STAFF_PROFILE_SUCCESS = 'UPDATE_STAFF_PROFILE_SUCCESS';
export const UPDATE_STAFF_PROFILE_FAILURE = 'UPDATE_STAFF_PROFILE_FAILURE';

export const FETCH_STOREFRONT_PENDING = 'FETCH_STOREFRONT_PENDING';
export const FETCH_STOREFRONT_SUCCESS = 'FETCH_STOREFRONT_SUCCESS';
export const FETCH_STOREFRONT_FAILURE = 'FETCH_STOREFRONT_FAILURE';

export const UPDATE_STOREFRONT_PENDING = 'UPDATE_STOREFRONT_PENDING';
export const UPDATE_STOREFRONT_SUCCESS = 'UPDATE_STOREFRONT_SUCCESS';
export const UPDATE_STOREFRONT_FAILURE = 'UPDATE_STOREFRONT_FAILURE';

export const TEMPLATE_SETTINGS_LOGO_UPLOAD_PENDING =
  'TEMPLATE_SETTINGS_LOGO_UPLOAD_PENDING';
export const TEMPLATE_SETTINGS_LOGO_UPLOAD_SUCCESS =
  'TEMPLATE_SETTINGS_LOGO_UPLOAD_SUCCESS';
export const TEMPLATE_SETTINGS_LOGO_UPLOAD_FAILURE =
  'TEMPLATE_SETTINGS_LOGO_UPLOAD_FAILURE';

export const TEMPLATE_SETTINGS_LOGO_DELETE_PENDING =
  'TEMPLATE_SETTINGS_LOGO_DELETE_PENDING';
export const TEMPLATE_SETTINGS_LOGO_DELETE_SUCCESS =
  'TEMPLATE_SETTINGS_LOGO_DELETE_SUCCESS';
export const TEMPLATE_SETTINGS_LOGO_DELETE_FAILURE =
  'TEMPLATE_SETTINGS_LOGO_DELETE_FAILURE';

export const TEMPLATE_SETTINGS_CAROUSEL_UPLOAD_PENDING =
  'TEMPLATE_SETTINGS_CAROUSEL_UPLOAD_PENDING';
export const TEMPLATE_SETTINGS_CAROUSEL_UPLOAD_SUCCESS =
  'TEMPLATE_SETTINGS_CAROUSEL_UPLOAD_SUCCESS';
export const TEMPLATE_SETTINGS_CAROUSEL_UPLOAD_FAILURE =
  'TEMPLATE_SETTINGS_CAROUSEL_UPLOAD_FAILURE';

export const TEMPLATE_SETTINGS_CAROUSEL_UPDATE_PENDING =
  'TEMPLATE_SETTINGS_CAROUSEL_UPDATE_PENDING';
export const TEMPLATE_SETTINGS_CAROUSEL_UPDATE_SUCCESS =
  'TEMPLATE_SETTINGS_CAROUSEL_UPDATE_SUCCESS';
export const TEMPLATE_SETTINGS_CAROUSEL_UPDATE_FAILURE =
  'TEMPLATE_SETTINGS_CAROUSEL_UPDATE_FAILURE';

export const TEMPLATE_SETTINGS_CAROUSEL_DELETE_PENDING =
  'TEMPLATE_SETTINGS_CAROUSEL_DELETE_PENDING';
export const TEMPLATE_SETTINGS_CAROUSEL_DELETE_SUCCESS =
  'TEMPLATE_SETTINGS_CAROUSEL_DELETE_SUCCESS';
export const TEMPLATE_SETTINGS_CAROUSEL_DELETE_FAILURE =
  'TEMPLATE_SETTINGS_CAROUSEL_DELETE_FAILURE';
